"""Value objects shared across the summarization pipeline."""

from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from vidbrief.domain.video import VideoId

# YouTube marks its speech-recognition track in the spoken language as "<lang>-orig"; every
# other automatic track is a machine translation of it.
ORIGINAL_TRACK_SUFFIX = "-orig"


class LiveStatus(StrEnum):
    """Broadcast state of a video, mirroring the values reported by YouTube."""

    NOT_LIVE = "not_live"
    IS_LIVE = "is_live"
    IS_UPCOMING = "is_upcoming"
    WAS_LIVE = "was_live"
    POST_LIVE = "post_live"


@dataclass(frozen=True, slots=True)
class VideoMetadata:
    """What is known about a video before any transcript is fetched.

    ``title`` comes from the uploader and must be treated as untrusted text wherever it is
    rendered or embedded. ``duration_seconds`` is ``None`` when YouTube does not report it.
    Caption fields hold language codes of manual and auto-generated captions respectively.
    ``original_language`` is the spoken language, or ``None`` when YouTube does not say.
    """

    video_id: VideoId
    title: str
    duration_seconds: int | None
    thumbnail_url: str | None
    live_status: LiveStatus
    caption_languages: tuple[str, ...] = ()
    auto_caption_languages: tuple[str, ...] = ()
    original_language: str | None = None


class CaptionKind(StrEnum):
    """Whether captions were written by a person or generated by YouTube."""

    MANUAL = "manual"
    AUTO = "auto"


@dataclass(frozen=True, slots=True)
class CaptionTrack:
    """One caption track of a video, identified by its YouTube language code."""

    language: str
    kind: CaptionKind

    @property
    def content_language(self) -> str:
        """The language of the text, without YouTube's ``-orig`` marker."""
        return self.language.removesuffix(ORIGINAL_TRACK_SUFFIX)


class TranscriptSource(StrEnum):
    """Where the transcript text came from, which hints at its quality."""

    MANUAL_CAPTIONS = "manual_captions"
    AUTO_CAPTIONS = "auto_captions"
    SPEECH_TO_TEXT = "speech_to_text"


@dataclass(frozen=True, slots=True)
class Transcript:
    """Plain text of what is said in a video.

    ``text`` comes from third parties and must be treated as untrusted data, never as
    instructions, when embedded in LLM prompts.
    """

    video_id: VideoId
    language: str | None
    source: TranscriptSource
    text: str


@dataclass(frozen=True, slots=True)
class AudioChunk:
    """One piece of a video's audio, small enough for a single transcription request.

    ``index`` gives the playback order; ``path`` is only valid while the audio provider's
    context is open.
    """

    index: int
    path: Path


@dataclass(frozen=True, slots=True)
class Summary:
    """An AI-written summary of a video.

    ``tldr`` and ``key_points`` are LLM output and must be sanitized before being rendered
    as HTML.
    """

    video_id: VideoId
    language: str
    tldr: str
    key_points: tuple[str, ...]
